version: '3.8'

services:
  kb-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      # 持久化数据
      - ./data:/app/data
      - ./logs:/app/logs
      - ./chroma_db:/app/chroma_db
      - ./models:/app/models
      # 缓存目录
      - kb-cache:/app/tmp/cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  kb-cache:
    driver: local